dist: trusty
sudo: required
language: cpp

notifications:
 email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - Q_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - Q_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode8
      env:
        - Q_EVAL="brew update && (brew outdated gcc5 || brew upgrade gcc5) && brew install gcc5 && CC=gcc-5 && CXX=g++-5"

before_install:
  - eval "${Q_EVAL}"

script:
 - cmake --version
 - mkdir build
 - cd build
 - cmake ..
 - cmake --build . -- -j4
 - ctest --output-on-failure
